#spring:
#  application:
#    name: tutorialspoint-java-application
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#  datasource:
#    username: root
#    password: 
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: mysql://localhost:3306/test
#server:
#  port: 8081 